#!/bin/sh

# TODO format/wrap comments in everything

case "$1" in
	# TODO *.git/ADD_EDIT.patch
	# TODO *.git/COMMIT_EDITMESSAGE) ;;
	*.md) exec markdownfmt -w "$1";;
	*.go) exec goreturns -w "$@";;
esac
