#!/bin/sh

# TODO format/wrap comments in everything

case "$1" in
	# TODO github (README.md, CONTRIBUTING.md, AUTHORS, LICENSE)
	# TODO * add a license header (acme-license -license bsd -date 2017 -authors AUTHORS)
	# TODO *.git/ADD_EDIT.patch
	# TODO *.git/COMMIT_EDITMESSAGE) ;;
	# TODO xml http://xmlsoft.org/xmllint.html
	# TODO .c .cpp .java .js .pb http://clang.llvm.org/docs/ClangFormat.html
	# TODO .py https://github.com/google/yapf
	# TODO .rb https://github.com/erniebrodeur/ruby-beautify
	# TODO .rs https://github.com/nrc/rustfmt/
	# TODO .js .html .css https://github.com/beautify-web/js-beautify
	# TODO .js http://eslint.org/ http://standardjs.com/
	# TODO .ts https://github.com/vvakame/typescript-formatter
	# TODO .html http://tidy.sourceforge.net/docs/tidy_man.html
	#*.css) exec js-beautifu -jnr "$1";;
	#*.html) exec js-beautify -jnr "$1";;
	*.js) exec clang-format -i -style=Google "$1";;
	*.md) exec markdownfmt -w "$1";;
	*.go) exec goreturns -w "$1";;
esac
